/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.nuttle.avro.bo.account;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AvroAccountProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroAccountProtocol\",\"namespace\":\"net.nuttle.avro.bo.account\",\"types\":[{\"type\":\"record\",\"name\":\"AvroAccountRequest\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"AvroAccountResponse\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"balance\",\"type\":\"float\"}]}],\"messages\":{\"getBalance\":{\"request\":[{\"name\":\"r\",\"type\":\"AvroAccountRequest\"}],\"response\":\"AvroAccountResponse\"}}}");
  net.nuttle.avro.bo.account.AvroAccountResponse getBalance(net.nuttle.avro.bo.account.AvroAccountRequest r) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AvroAccountProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = net.nuttle.avro.bo.account.AvroAccountProtocol.PROTOCOL;
    void getBalance(net.nuttle.avro.bo.account.AvroAccountRequest r, org.apache.avro.ipc.Callback<net.nuttle.avro.bo.account.AvroAccountResponse> callback) throws java.io.IOException;
  }
}