/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.nuttle.avro.bo.datafeed;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroDatafeedSchemaField extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroDatafeedSchemaField\",\"namespace\":\"net.nuttle.avro.bo.datafeed\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"dataType\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence dataType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroDatafeedSchemaField() {}

  /**
   * All-args constructor.
   */
  public AvroDatafeedSchemaField(java.lang.CharSequence name, java.lang.CharSequence dataType) {
    this.name = name;
    this.dataType = dataType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return dataType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: dataType = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'dataType' field.
   */
  public java.lang.CharSequence getDataType() {
    return dataType;
  }

  /**
   * Sets the value of the 'dataType' field.
   * @param value the value to set.
   */
  public void setDataType(java.lang.CharSequence value) {
    this.dataType = value;
  }

  /** Creates a new AvroDatafeedSchemaField RecordBuilder */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder newBuilder() {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder();
  }
  
  /** Creates a new AvroDatafeedSchemaField RecordBuilder by copying an existing Builder */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder newBuilder(net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder other) {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder(other);
  }
  
  /** Creates a new AvroDatafeedSchemaField RecordBuilder by copying an existing AvroDatafeedSchemaField instance */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder newBuilder(net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField other) {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroDatafeedSchemaField instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroDatafeedSchemaField>
    implements org.apache.avro.data.RecordBuilder<AvroDatafeedSchemaField> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence dataType;

    /** Creates a new Builder */
    private Builder() {
      super(net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dataType)) {
        this.dataType = data().deepCopy(fields()[1].schema(), other.dataType);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroDatafeedSchemaField instance */
    private Builder(net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField other) {
            super(net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dataType)) {
        this.dataType = data().deepCopy(fields()[1].schema(), other.dataType);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'dataType' field */
    public java.lang.CharSequence getDataType() {
      return dataType;
    }
    
    /** Sets the value of the 'dataType' field */
    public net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder setDataType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.dataType = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'dataType' field has been set */
    public boolean hasDataType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'dataType' field */
    public net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField.Builder clearDataType() {
      dataType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AvroDatafeedSchemaField build() {
      try {
        AvroDatafeedSchemaField record = new AvroDatafeedSchemaField();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.dataType = fieldSetFlags()[1] ? this.dataType : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
