/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.nuttle.avro.bo.datafeed;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AvroDatafeedProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroDatafeedProtocol\",\"namespace\":\"net.nuttle.avro.bo.datafeed\",\"types\":[{\"type\":\"record\",\"name\":\"AvroDatafeedLine\",\"fields\":[{\"name\":\"fields\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]},{\"type\":\"record\",\"name\":\"AvroDatafeedSchemaField\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"dataType\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"AvroDatafeedSchema\",\"fields\":[{\"name\":\"fields\",\"type\":{\"type\":\"array\",\"items\":\"AvroDatafeedSchemaField\"}}]},{\"type\":\"record\",\"name\":\"AvroDatafeedRequest\",\"fields\":[{\"name\":\"clientid\",\"type\":\"int\"},{\"name\":\"datafeedschema\",\"type\":\"AvroDatafeedSchema\"},{\"name\":\"lines\",\"type\":{\"type\":\"array\",\"items\":\"AvroDatafeedLine\"}}]},{\"type\":\"record\",\"name\":\"AvroDatafeedResponse\",\"fields\":[{\"name\":\"responseCode\",\"type\":\"int\"}]}],\"messages\":{\"getResult\":{\"request\":[{\"name\":\"r\",\"type\":\"AvroDatafeedRequest\"}],\"response\":\"AvroDatafeedResponse\"}}}");
  net.nuttle.avro.bo.datafeed.AvroDatafeedResponse getResult(net.nuttle.avro.bo.datafeed.AvroDatafeedRequest r) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AvroDatafeedProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = net.nuttle.avro.bo.datafeed.AvroDatafeedProtocol.PROTOCOL;
    void getResult(net.nuttle.avro.bo.datafeed.AvroDatafeedRequest r, org.apache.avro.ipc.Callback<net.nuttle.avro.bo.datafeed.AvroDatafeedResponse> callback) throws java.io.IOException;
  }
}