/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.nuttle.avro.bo.datafeed;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroDatafeedSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroDatafeedSchema\",\"namespace\":\"net.nuttle.avro.bo.datafeed\",\"fields\":[{\"name\":\"fields\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroDatafeedSchemaField\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"dataType\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField> fields;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroDatafeedSchema() {}

  /**
   * All-args constructor.
   */
  public AvroDatafeedSchema(java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField> fields) {
    this.fields = fields;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fields;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fields = (java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'fields' field.
   */
  public java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField> getFields() {
    return fields;
  }

  /**
   * Sets the value of the 'fields' field.
   * @param value the value to set.
   */
  public void setFields(java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField> value) {
    this.fields = value;
  }

  /** Creates a new AvroDatafeedSchema RecordBuilder */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder newBuilder() {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder();
  }
  
  /** Creates a new AvroDatafeedSchema RecordBuilder by copying an existing Builder */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder newBuilder(net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder other) {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder(other);
  }
  
  /** Creates a new AvroDatafeedSchema RecordBuilder by copying an existing AvroDatafeedSchema instance */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder newBuilder(net.nuttle.avro.bo.datafeed.AvroDatafeedSchema other) {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroDatafeedSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroDatafeedSchema>
    implements org.apache.avro.data.RecordBuilder<AvroDatafeedSchema> {

    private java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField> fields;

    /** Creates a new Builder */
    private Builder() {
      super(net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fields)) {
        this.fields = data().deepCopy(fields()[0].schema(), other.fields);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroDatafeedSchema instance */
    private Builder(net.nuttle.avro.bo.datafeed.AvroDatafeedSchema other) {
            super(net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.SCHEMA$);
      if (isValidValue(fields()[0], other.fields)) {
        this.fields = data().deepCopy(fields()[0].schema(), other.fields);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'fields' field */
    public java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField> getFields() {
      return fields;
    }
    
    /** Sets the value of the 'fields' field */
    public net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder setFields(java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField> value) {
      validate(fields()[0], value);
      this.fields = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'fields' field has been set */
    public boolean hasFields() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'fields' field */
    public net.nuttle.avro.bo.datafeed.AvroDatafeedSchema.Builder clearFields() {
      fields = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroDatafeedSchema build() {
      try {
        AvroDatafeedSchema record = new AvroDatafeedSchema();
        record.fields = fieldSetFlags()[0] ? this.fields : (java.util.List<net.nuttle.avro.bo.datafeed.AvroDatafeedSchemaField>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
