/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.nuttle.avro.bo.datafeed;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroDatafeedResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroDatafeedResponse\",\"namespace\":\"net.nuttle.avro.bo.datafeed\",\"fields\":[{\"name\":\"responseCode\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int responseCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroDatafeedResponse() {}

  /**
   * All-args constructor.
   */
  public AvroDatafeedResponse(java.lang.Integer responseCode) {
    this.responseCode = responseCode;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return responseCode;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: responseCode = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'responseCode' field.
   */
  public java.lang.Integer getResponseCode() {
    return responseCode;
  }

  /**
   * Sets the value of the 'responseCode' field.
   * @param value the value to set.
   */
  public void setResponseCode(java.lang.Integer value) {
    this.responseCode = value;
  }

  /** Creates a new AvroDatafeedResponse RecordBuilder */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder newBuilder() {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder();
  }
  
  /** Creates a new AvroDatafeedResponse RecordBuilder by copying an existing Builder */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder newBuilder(net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder other) {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder(other);
  }
  
  /** Creates a new AvroDatafeedResponse RecordBuilder by copying an existing AvroDatafeedResponse instance */
  public static net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder newBuilder(net.nuttle.avro.bo.datafeed.AvroDatafeedResponse other) {
    return new net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroDatafeedResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroDatafeedResponse>
    implements org.apache.avro.data.RecordBuilder<AvroDatafeedResponse> {

    private int responseCode;

    /** Creates a new Builder */
    private Builder() {
      super(net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.responseCode)) {
        this.responseCode = data().deepCopy(fields()[0].schema(), other.responseCode);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroDatafeedResponse instance */
    private Builder(net.nuttle.avro.bo.datafeed.AvroDatafeedResponse other) {
            super(net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.SCHEMA$);
      if (isValidValue(fields()[0], other.responseCode)) {
        this.responseCode = data().deepCopy(fields()[0].schema(), other.responseCode);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'responseCode' field */
    public java.lang.Integer getResponseCode() {
      return responseCode;
    }
    
    /** Sets the value of the 'responseCode' field */
    public net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder setResponseCode(int value) {
      validate(fields()[0], value);
      this.responseCode = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'responseCode' field has been set */
    public boolean hasResponseCode() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'responseCode' field */
    public net.nuttle.avro.bo.datafeed.AvroDatafeedResponse.Builder clearResponseCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroDatafeedResponse build() {
      try {
        AvroDatafeedResponse record = new AvroDatafeedResponse();
        record.responseCode = fieldSetFlags()[0] ? this.responseCode : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
